// src/pages/About.vue
<template>
    <div>
        <p>
            Hello! I am a  Baltimore-based front end web developer and UX/UI designer with a 
            knack for creating engaging, thoughtful user experiences. 
        </p>
        <p class="mt-4 mb-8">Currently <span class="underline">available</span> for freelance work.</p>
        <section class="flex justify-between mt-4">
            <div>
                <h2 class="mb-4">PREFERRED TOOLS</h2>
                <ul>
                    <li>Vue.js</li>
                    <li>Gatbsy.js</li>
                    <li>React</li>
                    <li>Tailwind CSS</li>
                    <li>Figma</li>
                </ul>
            </div>
            <div>
                <h2 class="mb-4">SKILLS</h2>
                <ul>
                    <li>Front End Development</li>
                    <li>UI/UX Design</li>
                    <li>Wireframes/Prototypes</li>
                    <li>User Journey Maps</li>
                    <li>UX Research</li>
                </ul>
            </div>
        </section>
    </div>
</template>

<script>

export default {
    name: 'About',
}
</script>

// src/components/about.jsx
import React from 'react';

import Arrow from '../components/arrow';

const About = () => (
    <div className="mt-24 w-1/2 m-auto flex flex-col h-screen justify-evenly pb-32">
        <div className="flex">
            {/* right side */}
            <div className="w-1/2">
                <div>
                    <h3 className="mb-4">SKILLS</h3>
                    <ol className="font-semibold">
                        <li>Front End Development</li>
                        <li>UI/UX Design</li>
                        <li>Wireframes</li>
                        <li>User Journey Maps</li>
                        <li>Personas</li>
                        <li>UX Research</li>
                    </ol>
                </div>
                <div className="mt-8">
                    <h3 className="mb-4">PREFERRED TOOLS</h3>
                    <ol className="font-semibold">
                        <li>Gatsby.js</li>
                        <li>React</li>
                        <li>Vue.js</li>
                        <li>Tailwind CSS</li>
                        <li>Figma</li>
                    </ol>
                </div>
            </div>
            {/* left side */}
            <div className="w-1/2">
                <h3 className="mb-4">ABOUT</h3>
                <p className="font-semibold mb-4">
                    Hello! I am a front end web developer with an affinity for meaningful user experiences. 
                    My client history includes users in commercial and personal spaces, 
                    however, my specialty lies in developing and designing healthcare applications.
                    I can work individually or support an existing development/design team. 
                    Looking forward to providing clear, concise designs and UX expertise to ambitious clients 
                    making their ideas a reality.
                </p>
                <p className="font-semibold">
                    Currently <span className="underline">available</span> for freelance work.
                </p>
            </div>
        </div>
        <Arrow />
    </div>
);

export default About;
