// src/components/sections/about.jsx
import React from 'react';
import { Link } from 'gatsby';

import Arrow from '../arrow';

const About = () => (
    <div className="pt-24 text-xs sm:text-base sm:w-1/2 m-auto flex flex-col h-screen justify-between pb-4" id="about">
        <div className="flex">
            {/* right side */}
            <div className="w-1/2">
                <div>
                    <h3 className="mb-4">SKILLS</h3>
                    <ol className="font-semibold">
                        <li>Front End Development</li>
                        <li>UI/UX Design</li>
                        <li>Wireframes</li>
                        <li>User Journey Maps</li>
                        <li>Personas</li>
                        <li>UX Research</li>
                    </ol>
                </div>
                <div className="mt-8">
                    <h3 className="mb-4">PREFERRED TOOLS</h3>
                    <ol className="font-semibold">
                        <li>Gatsby.js</li>
                        <li>React</li>
                        <li>Vue.js</li>
                        <li>Tailwind CSS</li>
                        <li>Figma</li>
                    </ol>
                </div>
            </div>
            {/* left side */}
            <div className="w-1/2">
                <h3 className="mb-4">ABOUT</h3>
                <p className="font-semibold mb-4">
                    Hello! I am a front end web developer aware of the importance of creating meaningful user experiences. I have designed and developed for both individuals as well as corporate clients, with much of my work focusing on healthcare applications. I can provide clear, concise designs and UX expertise either individually or as part of an existing development/design team.
                </p>
                <p className="font-semibold">
                    Currently <span className="underline"><Link to="/contact">available</Link></span> for freelance work.
                </p>
            </div>
        </div>
        <Arrow target="#projects"/>
    </div>
);

export default About;

// pages/about.vue
<template>
  <div>
    <p>
      Hello! I am a Baltimore-based front end web developer and UX/UI designer
      creating engaging, thoughtful user experiences.
    </p>
    <p class="mt-4 mb-8">
      Currently
      <router-link to="/contact" class="underline font-bold"
        >available</router-link
      >
      for freelance work.
    </p>

    <img src="~/assets/self.png" alt="profile picture" width="125px" />
    <section class="flex justify-between mt-4">
      <div>
        <h2 class="mb-4">PREFERRED TOOLS</h2>
        <ul>
          <li>Vue.js</li>
          <li>Nuxt.js</li>
          <li>React</li>
          <li>Tailwind CSS</li>
          <li>Figma</li>
        </ul>
      </div>
      <div>
        <h2 class="mb-4">SKILLS</h2>
        <ul>
          <li>Front End Development</li>
          <li>UI/UX Design</li>
          <li>Wireframes/Prototypes</li>
          <li>User Journey Maps</li>
          <li>UX Research</li>
        </ul>
      </div>
    </section>
  </div>
</template>

<script>
export default {
  name: 'About',
  head() {
    return {
      title: 'About | Allen Hansrisuk',
    };
  },
};
</script>
