// src/pages/contact.jsx
import React from 'react';
import { Link } from 'gatsby';

import PageLayout from '../components/page-layout';
import SEO from '../components/seo';


const IndexPage = ({data}) => {

return (
    <PageLayout>
        <SEO title="Contact" />
        <div className="h-screen flex flex-col justify-between pb-4 pt-40" id="top">
            <div className="m-auto mt-0 lg:w-1/2">
                <h2 className="mb-2 text-2xl text-center">CONTACT</h2>
                <div className="w-1/2 m-auto border-t border-black mb-4"></div>
                <form name="contact" method="POST" data-netlify="true" data-netlify-honeypot="bot-field" className="shadow-md rounded px-8 pt-6 pb-8 mb-4">
                    <input type="hidden" name="form-name" value="contact" />
                    <label htmlFor="name" className="block">NAME:</label>
                    <input 
                        type="text"
                        id="name"
                        name="name" 
                        size="40" 
                        className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                    /> 
                    <label htmlFor="email" className="block mt-4">EMAIL:</label>
                    <input 
                        type="email" 
                        name="email" 
                        className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"/>

                    <label htmlFor="message" className="block mt-4">MESSAGE:</label>
                    <textarea 
                        name="message" 
                        rows="12" 
                        className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
                    </textarea>
                    <div className="w-full flex justify-end mt-4">
                        <Link to="/" className="self-center mr-4 hover:underline">BACK</Link>
                        <button 
                            type="submit" 
                            className="block btn">
                                SEND
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </PageLayout>
)};

export default IndexPage;

// pages/contact.vue
<template>
  <div>
    <p class="mb-4 text-2xl">Get in touch!📫</p>

    <p class="mb-8">
      For all general inquiries, proposals, questions, etc., please use the
      contact form below and I will get in touch as soon as possible. Thank you!
    </p>
    <form
      name="contact-form"
      method="post"
      data-netlify="true"
      data-netlify-honeypot="bot-field"
    >
      <input type="hidden" name="form-name" value="contact-form" />

      <div class="mb-4">
        <label for="name" class="block mb-1">Name:</label>
        <input
          type="text"
          class="bg-black rounded-md border-2 border-white p-1 w-full text-white"
          name="name"
        />
      </div>

      <div class="mb-4">
        <label for="email" class="block">Email:</label>
        <input
          type="text"
          class="bg-black rounded-md border-2 border-white p-1 w-full text-white"
          name="email"
        />
      </div>

      <div class="mb-4">
        <label for="message" class="block">Message:</label>
        <textarea
          name="message"
          class="bg-black rounded-md border-2 border-white text-black p-1 w-full text-white"
          rows="8"
        />
      </div>

      <div class="flex justify-end">
        <button type="submit" class="rounded-lg p-2 border-2 font-bold">
          Submit
        </button>
      </div>
    </form>
  </div>
</template>

<script>
export default {
  name: 'Contact',
  head() {
    return {
      title: 'Contact | Allen Hansrisuk',
    };
  },
};
</script>
